// warning this file is generated by a tool do not modify


#define SHADER_DECLARATION(_x) #_x

static const char canvas_video_frag_bytes[] = SHADER_DECLARATION(
\n#version 100\n
\n#define GLSL_VERSION_100\n
\n#define GLSL_FRAG\n
/* ===========================================================================
 *
 * Copyright (c) 2019-2021 Disney Streaming Technology LLC. All rights reserved.
 *
 * ==========================================================================*/

/*
shader_binding_locations.h

macro definitions for sharing between glsl/c so enum values can be shared between core and shaders for uniform/texture binding locations.
*/

\n#ifndef _SHADER_BINDING_LOCATIONS_HEADER_1234124412\n
\n#define _SHADER_BINDING_LOCATIONS_HEADER_1234124412\n

\n#define U_MVP_BINDING 0\n
\n#define U_VIEWPORT_BINDING 1\n
\n#define U_TEX0_BINDING 2\n
\n#define U_TEX1_BINDING 3\n
\n#define U_FILL_BINDING 4\n
\n#define U_THRESHOLD_BINDING 5\n

\n#endif\n
/* ===========================================================================
 *
 * Copyright (c) 2019-2020 Disney Streaming Technology LLC. All rights reserved.
 *
 * ==========================================================================*/

\n#ifdef GLSL_VERSION_450\n
\n#define LAYOUT(binding_declaration) layout(binding_declaration)\n
\n#define UNIFORM_STRUCT_DEF(struct_name, def) struct_name{def};\n
\n#ifdef GLSL_FRAG\n
out vec4 frag_color;
\n#define gl_FragColor frag_color\n
\n#endif\n
\n#else // glsl #version 100 support\n
\n#define LAYOUT(binding_declaration)\n
\n#define UNIFORM_STRUCT_DEF(struct_name, def) def\n
\n#ifndef GLSL_FRAG\n
\n#define in attribute\n
\n#define out varying\n
\n#else\n
\n#define in varying\n
\n#endif\n
\n#endif\n
/* ===========================================================================
 *
 * Copyright (c) 2019-2020 Disney Streaming Technology LLC. All rights reserved.
 *
 * ==========================================================================*/

/*
canvas_video.frag

cg(canvas) video fragment shader
*/

\n#ifdef GL_ES\n
precision lowp float;
\n#endif\n

LAYOUT(binding = U_TEX0_BINDING) uniform sampler2D u_tex0;
LAYOUT(binding = U_TEX1_BINDING) uniform sampler2D u_tex1;

LAYOUT(binding = U_FILL_BINDING) uniform UNIFORM_STRUCT_DEF(fill, vec4 u_fill;)

in vec4 v_var;

void main() {
    float alpha = v_var.a;
    vec2 chroma = texture2D(u_tex0, v_var.xy).rg;
    float luminance = texture2D(u_tex1, v_var.xy).r;
    vec3 YCbCr = vec3(luminance, chroma);

    YCbCr *= 1.0;
    YCbCr -= vec3(0.0625, 0.5, 0.5);
    
    vec3 rgb = vec3(dot(vec3(1.1644, 0.0, 1.7927), YCbCr), // R
                dot(vec3(1.1644, -0.2133, -0.5329), YCbCr), // G
                dot(vec3(1.1644, 2.1124, 0.0), YCbCr)); // B
                        
    gl_FragColor = vec4(rgb * u_fill.rgb, 1.0);
}
);
static const const_mem_region_t canvas_video_frag_program = {{.ptr = canvas_video_frag_bytes}, .size = ARRAY_SIZE(canvas_video_frag_bytes)};

#undef SHADER_DECLARATION