/* ===========================================================================
 *
 * Copyright (c) 2019-2020 Disney Streaming Technology LLC. All rights reserved.
 *
 * ==========================================================================*/

/*
glft.h

OpenGL function table. Only put stuff in here we use.
*/

#ifdef __cplusplus
extern "C" {
#endif

/* GLES 2.0 */
#if defined(GL_ES)
#ifdef GL_VAOS
REQUIRE(OES_vertex_array_object)
LOAD_OES(glBindVertexArray, GLBINDVERTEXARRAY)
LOAD_OES(glGenVertexArrays, GLGENVERTEXARRAY)
LOAD_OES(glDeleteVertexArrays, GLDELETEVERTEXARRAYS)
#endif

//LOAD(glTextureStorage2DEXT, GLTEXTURESTORAGE2DEXT)

//LOAD(glClipControlEXT, GLCLIPCONTROLEXT)
REQUIRE(EXT_discard_framebuffer)
LOAD(glDiscardFramebufferEXT, GLDISCARDFRAMEBUFFEREXT)

#if defined(GL_DEBUG_CONTEXT)
REQUIRE(KHR_debug_output)
LOAD(glDebugMessageCallbackKHR, GLDEBUGMESSAGECALLBACKKHR)
LOAD(glDebugMessageInsertKHR, GLDEBUGMESSAGEINSERTKHR)
LOAD(glDebugMessageControlKHR, GLDEBUGMESSAGECONTROLKHR)
#endif

#ifdef _STB_NATIVE
CHECK(OES_EGL_image_external)
REQUIRE_EGL(KHR_image_base)
REQUIRE_EGL(KHR_gl_texture_2D_image)

LOAD(eglCreateImageKHR, EGLCREATEIMAGEKHR)
LOAD(glEGLImageTargetTexture2DOES, GLEGLIMAGETARGETTEXTURE2DOES)
#endif

#elif defined(GL_CORE)
/* GL 1.2 */

/*LOAD(glDrawRangeElements, GLDRAWRANGEELEMENTS)*/
/*LOAD(glTexImage3D, GLTEXIMAGE3D)*/
/*LOAD(glTexSubImage3D, GLTEXSUBIMAGE3D)*/
/*LOAD(glCopyTexSubImage3D, GLCOPYTEXSUBIMAGE3D)*/

REQUIRE(EXT_texture_compression_s3tc)

/* GL 1.3 */
#ifndef GL_DSA
LOAD(glActiveTexture, GLACTIVETEXTURE)
#endif
/*LOAD(glSampleCoverage, GLSAMPLECOVERAGE)*/
/*LOAD(glCompressedTexImage3D, GLCOMPRESSEDTEXIMAGE3D)*/
LOAD(glCompressedTexImage2D, GLCOMPRESSEDTEXIMAGE2D)
/*LOAD(glCompressedTexImage1D, GLCOMPRESSEDTEXIMAGE1D)*/
/*LOAD(glCompressedTexSubImage3D, GLCOMPRESSEDTEXSUBIMAGE3D)*/
#ifndef GL_DSA
LOAD(glCompressedTexSubImage2D, GLCOMPRESSEDTEXSUBIMAGE2D)
#endif
/*LOAD(glCompressedTexSubImage1D, GLCOMPRESSEDTEXSUBIMAGE1D)*/
/*LOAD(glGetCompressedTexImage, GLGETCOMPRESSEDTEXIMAGE)*/

/* GL 1.4 */

LOAD(glBlendFuncSeparate, GLBLENDFUNCSEPARATE)
LOAD(glBlendColor, GLBLENDCOLOR)

/* GL 1.5 */
/*LOAD(glGenQueries, GLGENQUERIES)*/
/*LOAD(glDeleteQueries, GLDELETEQUERIES)*/
/*LOAD(glIsQuery, GLISQUERY)*/
/*LOAD(glBeginQuery, GLBEGINQUERY)*/
/*LOAD(glEndQuery, GLENDQUERY)*/
/*LOAD(glGetQueryiv, GLGETQUERYIV)*/
/*LOAD(glGetQueryObjectiv, GLGETQUERYOBJECTIV)*/
/*LOAD(glGetQueryObjectuiv, GLGETQUERYOBJECTUIV)*/
#if !(defined(GL_DSA) && defined(GL_VAOS))
LOAD(glBindBuffer, GLBINDBUFFER)
#endif
#ifndef GL_DSA
LOAD(glGenBuffers, GLGENBUFFERS)
LOAD(glIsBuffer, GLISBUFFER)
LOAD(glBufferData, GLBUFFERDATA)
LOAD(glBufferSubData, GLBUFFERSUBDATA)
#endif
LOAD(glDeleteBuffers, GLDELETEBUFFERS)

/* GL 2.0 */

LOAD(glBlendEquationSeparate, GLBLENDEQUATIONSEPARATE)
#ifndef GL_DSA
LOAD(glDrawBuffers, GLDRAWBUFFERS)
#endif
LOAD(glStencilOpSeparate, GLSTENCILOPSEPARATE)
LOAD(glStencilFuncSeparate, GLSTENCILFUNCSEPARATE)
LOAD(glStencilMaskSeparate, GLSTENCILMASKSEPARATE)
LOAD(glAttachShader, GLATTACHSHADER)
LOAD(glBindAttribLocation, GLBINDATTRIBLOCATION)
LOAD(glCompileShader, GLCOMPILESHADER)
LOAD(glCreateProgram, GLCREATEPROGRAM)
LOAD(glCreateShader, GLCREATESHADER)
LOAD(glDeleteProgram, GLDELETEPROGRAM)
LOAD(glDeleteShader, GLDELETESHADER)
LOAD(glDetachShader, GLDETACHSHADER)
#if !(defined(GL_DSA) && defined(GL_VAOS))
LOAD(glDisableVertexAttribArray, GLDISABLEVERTEXATTRIBARRAY)
LOAD(glEnableVertexAttribArray, GLENABLEVERTEXATTRIBARRAY)
LOAD(glVertexAttribPointer, GLVERTEXATTRIBPOINTER)
#elif defined(GL_FRAMEBUFFER_BLIT_PROGRAM)
LOAD(glEnableVertexAttribArray, GLENABLEVERTEXATTRIBARRAY)
LOAD(glVertexAttribPointer, GLVERTEXATTRIBPOINTER)
#endif
/*LOAD(glGetActiveAttrib, GLGETACTIVEATTRIB)*/
/*LOAD(glGetActiveUniform, GLGETACTIVEUNIFORM)*/
/*LOAD(glGetAttachedShaders, GLGETATTACHEDSHADERS)*/
LOAD(glGetAttribLocation, GLGETATTRIBLOCATION)
LOAD(glGetProgramiv, GLGETPROGRAMIV)
LOAD(glGetProgramInfoLog, GLGETPROGRAMINFOLOG)
LOAD(glGetShaderiv, GLGETSHADERIV)
LOAD(glGetShaderInfoLog, GLGETSHADERINFOLOG)
/*LOAD(glGetShaderSource, GLGETSHADERSOURCE)*/
LOAD(glGetUniformLocation, GLGETUNIFORMLOCATION)
/*LOAD(glGetUniformfv, GLGETUNIFORMFV)*/
/*LOAD(glGetUniformiv, GLGETUNIFORMIV)*/
/*LOAD(glGetVertexAttribdv, GLGETVERTEXATTRIBDV)*/
/*LOAD(glGetVertexAttribfv, GLGETVERTEXATTRIBFV)*/
/*LOAD(glGetVertexAttribiv, GLGETVERTEXATTRIBIV)*/
/*LOAD(glGetVertexAttribPointerv, GLGETVERTEXATTRIBPOINTERV)*/
/*LOAD(glIsProgram, GLISPROGRAM)*/
/*LOAD(glIsShader, GLISSHADER)*/
LOAD(glLinkProgram, GLLINKPROGRAM)
LOAD(glShaderSource, GLSHADERSOURCE)
LOAD(glUseProgram, GLUSEPROGRAM)
LOAD(glUniform1f, GLUNIFORM1F)
/*LOAD(glUniform2f, GLUNIFORM2F)*/
/*LOAD(glUniform3f, GLUNIFORM3F)*/
/*LOAD(glUniform4f, GLUNIFORM4F)*/
LOAD(glUniform1i, GLUNIFORM1I)
/*LOAD(glUniform2i, GLUNIFORM2I)*/
/*LOAD(glUniform3i, GLUNIFORM3I)*/
/*LOAD(glUniform4i, GLUNIFORM4I)*/
/*LOAD(glUniform1fv, GLUNIFORM1FV)*/
LOAD(glUniform2fv, GLUNIFORM2FV)
/*LOAD(glUniform3fv, GLUNIFORM3FV)*/
LOAD(glUniform4fv, GLUNIFORM4FV)
/*LOAD(glUniform1iv, GLUNIFORM1IV)*/
/*LOAD(glUniform2iv, GLUNIFORM2IV)*/
/*LOAD(glUniform3iv, GLUNIFORM3IV)*/
/*LOAD(glUniform4iv, GLUNIFORM4IV)*/
/*LOAD(glUniformMatrix2fv, GLUNIFORMMATRIX2FV)*/
/*LOAD(glUniformMatrix3fv, GLUNIFORMMATRIX3FV)*/
LOAD(glUniformMatrix4fv, GLUNIFORMMATRIX4FV)
/*LOAD(glValidateProgram, GLVALIDATEPROGRAM)*/

/* GL 3.0 */

/*LOAD(glBindBufferRange, GLBINDBUFFERRANGE)*/
/*LOAD(glBindBufferBase, GLBINDBUFFERBASE)*/
/*LOAD(glTransformFeedbackVaryings, GLTRANSFORMFEEDBACKVARYINGS)*/
/*LOAD(glGetTransformFeedbackVarying, GLGETTRANSFORMFEEDBACKVARYING)*/
/*LOAD(glClampColor, GLCLAMPCOLOR)*/
/*LOAD(glBeginConditionalRender, GLBEGINCONDITIONALRENDER)*/
/*LOAD(glEndConditionalRender, GLENDCONDITIONALRENDER)*/
/*LOAD(glVertexAttribIPointer, GLVERTEXATTRIBIPOINTER)*/
/*LOAD(glBindFragDataLocation, GLBINDFRAGDATALOCATION)*/
/*LOAD(glGetFragDataLocation, GLGETFRAGDATALOCATION)*/
/*LOAD(glUniform1ui, GLUNIFORM1UI)*/
/*LOAD(glUniform2ui, GLUNIFORM2UI)*/
/*LOAD(glUniform3ui, GLUNIFORM3UI)*/
/*LOAD(glUniform4ui, GLUNIFORM4UI)*/
/*LOAD(glUniform1uiv, GLUNIFORM1UIV)*/
/*LOAD(glUniform2uiv, GLUNIFORM2UIV)*/
/*LOAD(glUniform3uiv, GLUNIFORM3UIV)*/
/*LOAD(glUniform4uiv, GLUNIFORM4UIV)*/
/*LOAD(glTexParameterIiv, GLTEXPARAMETERIIV)*/
/*LOAD(glTexParameterIuiv, GLTEXPARAMETERIUIV)*/
/*LOAD(glGetTexParameterIiv, GLGETTEXPARAMETERIIV)*/
/*LOAD(glGetTexParameterIuiv, GLGETTEXPARAMETERIUIV)*/
/*LOAD(glClearBufferiv, GLCLEARBUFFERIV)*/
/*LOAD(glClearBufferuiv, GLCLEARBUFFERUIV)*/
/*LOAD(glClearBufferfv, GLCLEARBUFFERFV)*/
/*LOAD(glClearBufferfi, GLCLEARBUFFERFI)*/
/*LOAD(glGetStringi, GLGETSTRINGI)*/
/*LOAD(glIsRenderbuffer, GLISRENDERBUFFER)*/

LOAD(glDeleteRenderbuffers, GLDELETERENDERBUFFERS)
/*LOAD(glGetRenderbufferParameteriv, GLGETRENDERBUFFERPARAMETERIV)*/
/*LOAD(glIsFramebuffer, GLISFRAMEBUFFER)*/
LOAD(glBindFramebuffer, GLBINDFRAMEBUFFER)
LOAD(glDeleteFramebuffers, GLDELETEFRAMEBUFFERS)
#ifndef GL_DSA
LOAD(glBindRenderbuffer, GLBINDRENDERBUFFER)
LOAD(glGenFramebuffers, GLGENFRAMEBUFFERS)
LOAD(glGenRenderbuffers, GLGENRENDERBUFFERS)
LOAD(glCheckFramebufferStatus, GLCHECKFRAMEBUFFERSTATUS)
LOAD(glRenderbufferStorage, GLRENDERBUFFERSTORAGE)
LOAD(glFramebufferRenderbuffer, GLFRAMEBUFFERRENDERBUFFER)
LOAD(glFramebufferTexture2D, GLFRAMEBUFFERTEXTURE2D)
#endif
/*LOAD(glFramebufferTexture1D, GLFRAMEBUFFERTEXTURE1D)*/
/*LOAD(glFramebufferTexture3D, GLFRAMEBUFFERTEXTURE3D)*/
/*LOAD(glGetFramebufferAttachmentParameteriv, GLGETFRAMEBUFFERATTACHMENTPARAMETERIV)*/
/*LOAD(glGenerateMipmap, GLGENERATEMIPMAP)*/
#ifndef GL_DSA
LOAD(glBlitFramebuffer, GLBLITFRAMEBUFFER)
#endif
/*LOAD(glRenderbufferStorageMultisample, GLRENDERBUFFERSTORAGEMULTISAMPLE)*/
/*LOAD(glFramebufferTextureLayer, GLFRAMEBUFFERTEXTURELAYER)*/
/*LOAD(glMapBufferRange, GLMAPBUFFERRANGE)*/
/*LOAD(glFlushMappedBufferRange, GLFLUSHMAPPEDBUFFERRANGE)*/

LOAD(glBindVertexArray, GLBINDVERTEXARRAY)
LOAD(glDeleteVertexArrays, GLDELETEVERTEXARRAYS)

#if defined(GL_FRAMEBUFFER_BLIT_PROGRAM) || ((!(defined(GL_VAOS) && defined(GL_DSA))) && (GLVERSION >= 320))
LOAD(glGenVertexArrays, GLGENVERTEXARRAYS)
#endif
/*LOAD(glIsVertexArray, GLISVERTEXARRAY)*/

/* GL 3.1 */

/*LOAD(glDrawArraysInstanced, GLDRAWARRAYSINSTANCED)*/
/*LOAD(glDrawElementsInstanced, GLDRAWELEMENTSINSTANCED)*/
/*LOAD(glTexBuffer, GLTEXBUFFER)*/
/*LOAD(glPrimitiveRestartIndex, GLPRIMITIVERESTARTINDEX)*/
/*LOAD(glCopyBufferSubData, GLCOPYBUFFERSUBDATA)*/
/*LOAD(glGetUniformIndices, GLGETUNIFORMINDICES)*/
/*LOAD(glGetActiveUniformsiv, GLGETACTIVEUNIFORMSIV)*/
/*LOAD(glGetActiveUniformName, GLGETACTIVEUNIFORMNAME)*/
/*LOAD(glGetUniformBlockIndex, GLGETUNIFORMBLOCKINDEX)*/
/*LOAD(glGetActiveUniformBlockiv, GLGETACTIVEUNIFORMBLOCKIV)*/
/*LOAD(glGetActiveUniformBlockName, GLGETACTIVEUNIFORMBLOCKNAME)*/
/*LOAD(glUniformBlockBinding, GLUNIFORMBLOCKBINDING)*/

/* GL 3.2 */

/*LOAD(glDrawElementsBaseVertex, GLDRAWELEMENTSBASEVERTEX)*/

/*LOAD(glDrawRangeElementsBaseVertex, GLDRAWRANGEELEMENTSBASEVERTEX)*/
/*LOAD(glDrawElementsInstancedBaseVertex, GLDRAWELEMENTSINSTANCEDBASEVERTEX)*/
/*LOAD(glMultiDrawElementsBaseVertex, GLMULTIDRAWELEMENTSBASEVERTEX)*/
/*LOAD(glProvokingVertex, GLPROVOKINGVERTEX)*/
/*LOAD(glFenceSync, GLFENCESYNC)*/
/*LOAD(glIsSync, GLISSYNC)*/
/*LOAD(glDeleteSync, GLDELETESYNC)*/
/*LOAD(glClientWaitSync, GLCLIENTWAITSYNC)*/
/*LOAD(glWaitSync, GLWAITSYNC)*/
/*LOAD(glGetInteger64v, GLGETINTEGER64V)*/
/*LOAD(glGetSynciv, GLGETSYNCIV)*/
/*LOAD(glGetInteger64i_v, GLGETINTEGER64I_V)*/
/*LOAD(glGetBufferParameteri64v, GLGETBUFFERPARAMETERI64V)*/
/*LOAD(glFramebufferTexture, GLFRAMEBUFFERTEXTURE)*/
/*LOAD(glTexImage2DMultisample, GLTEXIMAGE2DMULTISAMPLE)*/
/*LOAD(glTexImage3DMultisample, GLTEXIMAGE3DMULTISAMPLE)*/
/*LOAD(glGetMultisamplefv, GLGETMULTISAMPLEFV)*/
/*LOAD(glSampleMaski, GLSAMPLEMASKI)*/

/* GL 3.3 */
#if GLVERSION >= 330

LOAD(glBindFragDataLocationIndexed, GLBINDFRAGDATALOCATIONINDEXED)
LOAD(glGetFragDataIndex, GLGETFRAGDATAINDEX)
LOAD(glGenSamplers, GLGENSAMPLERS)
LOAD(glDeleteSamplers, GLDELETESAMPLERS)
LOAD(glIsSampler, GLISSAMPLER)
LOAD(glBindSampler, GLBINDSAMPLER)
LOAD(glSamplerParameteri, GLSAMPLERPARAMETERI)
LOAD(glSamplerParameteriv, GLSAMPLERPARAMETERIV)
LOAD(glSamplerParameterf, GLSAMPLERPARAMETERF)
LOAD(glSamplerParameterfv, GLSAMPLERPARAMETERFV)
LOAD(glSamplerParameterIiv, GLSAMPLERPARAMETERIIV)
LOAD(glSamplerParameterIuiv, GLSAMPLERPARAMETERIUIV)
LOAD(glGetSamplerParameteriv, GLGETSAMPLERPARAMETERIV)
LOAD(glGetSamplerParameterIiv, GLGETSAMPLERPARAMETERIIV)
LOAD(glGetSamplerParameterfv, GLGETSAMPLERPARAMETERFV)
LOAD(glGetSamplerParameterIuiv, GLGETSAMPLERPARAMETERIUIV)
LOAD(glQueryCounter, GLQUERYCOUNTER)
LOAD(glGetQueryObjecti64v, GLGETQUERYOBJECTI64V)
LOAD(glGetQueryObjectui64v, GLGETQUERYOBJECTUI64V)
LOAD(glVertexAttribDivisor, GLVERTEXATTRIBDIVISOR)

#else

REQUIRE(ARB_sampler_objects)
LOAD(glGenSamplers, GLGENSAMPLERS)
LOAD(glDeleteSamplers, GLDELETESAMPLERS)
/*LOAD(glIsSampler, GLISSAMPLER)*/
LOAD(glBindSampler, GLBINDSAMPLER)
LOAD(glSamplerParameteri, GLSAMPLERPARAMETERI)
/*LOAD(glSamplerParameteriv, GLSAMPLERPARAMETERIV)*/
/*LOAD(glSamplerParameterf, GLSAMPLERPARAMETERF)*/
LOAD(glSamplerParameterfv, GLSAMPLERPARAMETERFV)
/*LOAD(glSamplerParameterIiv, GLSAMPLERPARAMETERIIV)*/
/*LOAD(glSamplerParameterIuiv, GLSAMPLERPARAMETERIUIV)*/
/*LOAD(glGetSamplerParameteriv, GLGETSAMPLERPARAMETERIV)*/
/*LOAD(glGetSamplerParameterIiv, GLGETSAMPLERPARAMETERIIV)*/
/*LOAD(glGetSamplerParameterfv, GLGETSAMPLERPARAMETERFV)*/
/*LOAD(glGetSamplerParameterIuiv, GLGETSAMPLERPARAMETERIUIV)*/

#endif

/* GL 4.0 */

#if GLVERSION >= 400
LOAD(glMinSampleShading, GLMINSAMPLESHADING)
LOAD(glBlendEquationi, GLBLENDEQUATIONI)
LOAD(glBlendEquationSeparatei, GLBLENDEQUATIONSEPARATEI)
LOAD(glBlendFunci, GLBLENDFUNCI)
LOAD(glBlendFuncSeparatei, GLBLENDFUNCSEPARATEI)
LOAD(glDrawArraysIndirect, GLDRAWARRAYSINDIRECT)
LOAD(glDrawElementsIndirect, GLDRAWELEMENTSINDIRECT)
LOAD(glUniform1d, GLUNIFORM1D)
LOAD(glUniform2d, GLUNIFORM2D)
LOAD(glUniform3d, GLUNIFORM3D)
LOAD(glUniform4d, GLUNIFORM4D)
LOAD(glUniform1dv, GLUNIFORM1DV)
LOAD(glUniform2dv, GLUNIFORM2DV)
LOAD(glUniform3dv, GLUNIFORM3DV)
LOAD(glUniform4dv, GLUNIFORM4DV)
LOAD(glUniformMatrix2dv, GLUNIFORMMATRIX2DV)
LOAD(glUniformMatrix3dv, GLUNIFORMMATRIX3DV)
LOAD(glUniformMatrix4dv, GLUNIFORMMATRIX4DV)
LOAD(glUniformMatrix2x3dv, GLUNIFORMMATRIX2X3DV)
LOAD(glUniformMatrix2x4dv, GLUNIFORMMATRIX2X4DV)
LOAD(glUniformMatrix3x2dv, GLUNIFORMMATRIX3X2DV)
LOAD(glUniformMatrix3x4dv, GLUNIFORMMATRIX3X4DV)
LOAD(glUniformMatrix4x2dv, GLUNIFORMMATRIX4X2DV)
LOAD(glUniformMatrix4x3dv, GLUNIFORMMATRIX4X3DV)
LOAD(glGetUniformdv, GLGETUNIFORMDV)
LOAD(glGetSubroutineUniformLocation, GLGETSUBROUTINEUNIFORMLOCATION)
LOAD(glGetSubroutineIndex, GLGETSUBROUTINEINDEX)
LOAD(glGetActiveSubroutineUniformiv, GLGETACTIVESUBROUTINEUNIFORMIV)
LOAD(glGetActiveSubroutineUniformName, GLGETACTIVESUBROUTINEUNIFORMNAME)
LOAD(glGetActiveSubroutineName, GLGETACTIVESUBROUTINENAME)
LOAD(glUniformSubroutinesuiv, GLUNIFORMSUBROUTINESUIV)
LOAD(glGetUniformSubroutineuiv, GLGETUNIFORMSUBROUTINEUIV)
LOAD(glGetProgramStageiv, GLGETPROGRAMSTAGEIV)
LOAD(glPatchParameteri, GLPATCHPARAMETERI)
LOAD(glPatchParameterfv, GLPATCHPARAMETERFV)
LOAD(glBindTransformFeedback, GLBINDTRANSFORMFEEDBACK)
LOAD(glDeleteTransformFeedbacks, GLDELETETRANSFORMFEEDBACKS)
LOAD(glGenTransformFeedbacks, GLGENTRANSFORMFEEDBACKS)
LOAD(glIsTransformFeedback, GLISTRANSFORMFEEDBACK)
LOAD(glPauseTransformFeedback, GLPAUSETRANSFORMFEEDBACK)
LOAD(glResumeTransformFeedback, GLRESUMETRANSFORMFEEDBACK)
LOAD(glDrawTransformFeedback, GLDRAWTRANSFORMFEEDBACK)
LOAD(glDrawTransformFeedbackStream, GLDRAWTRANSFORMFEEDBACKSTREAM)
LOAD(glBeginQueryIndexed, GLBEGINQUERYINDEXED)
LOAD(glEndQueryIndexed, GLENDQUERYINDEXED)
LOAD(glGetQueryIndexediv, GLGETQUERYINDEXEDIV)
#endif

/* GL 4.1 */
#if GLVERSION >= 410
LOAD(glReleaseShaderCompiler, GLRELEASESHADERCOMPILER)
LOAD(glShaderBinary, GLSHADERBINARY)
LOAD(glGetShaderPrecisionFormat, GLGETSHADERPRECISIONFORMAT)
LOAD(glDepthRangef, GLDEPTHRANGEF)
LOAD(glClearDepthf, GLCLEARDEPTHF)
LOAD(glGetProgramBinary, GLGETPROGRAMBINARY)
LOAD(glProgramBinary, GLPROGRAMBINARY)
LOAD(glProgramParameteri, GLPROGRAMPARAMETERI)
LOAD(glUseProgramStages, GLUSEPROGRAMSTAGES)
LOAD(glActiveShaderProgram, GLACTIVESHADERPROGRAM)
LOAD(glCreateShaderProgramv, GLCREATESHADERPROGRAMV)
LOAD(glBindProgramPipeline, GLBINDPROGRAMPIPELINE)
LOAD(glDeleteProgramPipelines, GLDELETEPROGRAMPIPELINES)
LOAD(glGenProgramPipelines, GLGENPROGRAMPIPELINES)
LOAD(glIsProgramPipeline, GLISPROGRAMPIPELINE)
LOAD(glGetProgramPipelineiv, GLGETPROGRAMPIPELINEIV)
LOAD(glProgramUniform1i, GLPROGRAMUNIFORM1I)
LOAD(glProgramUniform1iv, GLPROGRAMUNIFORM1IV)
LOAD(glProgramUniform1f, GLPROGRAMUNIFORM1F)
LOAD(glProgramUniform1fv, GLPROGRAMUNIFORM1FV)
LOAD(glProgramUniform1d, GLPROGRAMUNIFORM1D)
LOAD(glProgramUniform1dv, GLPROGRAMUNIFORM1DV)
LOAD(glProgramUniform1ui, GLPROGRAMUNIFORM1UI)
LOAD(glProgramUniform1uiv, GLPROGRAMUNIFORM1UIV)
LOAD(glProgramUniform2i, GLPROGRAMUNIFORM2I)
LOAD(glProgramUniform2iv, GLPROGRAMUNIFORM2IV)
LOAD(glProgramUniform2f, GLPROGRAMUNIFORM2F)
LOAD(glProgramUniform2fv, GLPROGRAMUNIFORM2FV)
LOAD(glProgramUniform2d, GLPROGRAMUNIFORM2D)
LOAD(glProgramUniform2dv, GLPROGRAMUNIFORM2DV)
LOAD(glProgramUniform2ui, GLPROGRAMUNIFORM2UI)
LOAD(glProgramUniform2uiv, GLPROGRAMUNIFORM2UIV)
LOAD(glProgramUniform3i, GLPROGRAMUNIFORM3I)
LOAD(glProgramUniform3iv, GLPROGRAMUNIFORM3IV)
LOAD(glProgramUniform3f, GLPROGRAMUNIFORM3F)
LOAD(glProgramUniform3fv, GLPROGRAMUNIFORM3FV)
LOAD(glProgramUniform3d, GLPROGRAMUNIFORM3D)
LOAD(glProgramUniform3dv, GLPROGRAMUNIFORM3DV)
LOAD(glProgramUniform3ui, GLPROGRAMUNIFORM3UI)
LOAD(glProgramUniform3uiv, GLPROGRAMUNIFORM3UIV)
LOAD(glProgramUniform4i, GLPROGRAMUNIFORM4I)
LOAD(glProgramUniform4iv, GLPROGRAMUNIFORM4IV)
LOAD(glProgramUniform4f, GLPROGRAMUNIFORM4F)
LOAD(glProgramUniform4fv, GLPROGRAMUNIFORM4FV)
LOAD(glProgramUniform4d, GLPROGRAMUNIFORM4D)
LOAD(glProgramUniform4dv, GLPROGRAMUNIFORM4DV)
LOAD(glProgramUniform4ui, GLPROGRAMUNIFORM4UI)
LOAD(glProgramUniform4uiv, GLPROGRAMUNIFORM4UIV)
LOAD(glProgramUniformMatrix2fv, GLPROGRAMUNIFORMMATRIX2FV)
LOAD(glProgramUniformMatrix3fv, GLPROGRAMUNIFORMMATRIX3FV)
LOAD(glProgramUniformMatrix4fv, GLPROGRAMUNIFORMMATRIX4FV)
LOAD(glProgramUniformMatrix2dv, GLPROGRAMUNIFORMMATRIX2DV)
LOAD(glProgramUniformMatrix3dv, GLPROGRAMUNIFORMMATRIX3DV)
LOAD(glProgramUniformMatrix4dv, GLPROGRAMUNIFORMMATRIX4DV)
LOAD(glProgramUniformMatrix2x3fv, GLPROGRAMUNIFORMMATRIX2X3FV)
LOAD(glProgramUniformMatrix3x2fv, GLPROGRAMUNIFORMMATRIX3X2FV)
LOAD(glProgramUniformMatrix2x4fv, GLPROGRAMUNIFORMMATRIX2X4FV)
LOAD(glProgramUniformMatrix4x2fv, GLPROGRAMUNIFORMMATRIX4X2FV)
LOAD(glProgramUniformMatrix3x4fv, GLPROGRAMUNIFORMMATRIX3X4FV)
LOAD(glProgramUniformMatrix4x3fv, GLPROGRAMUNIFORMMATRIX4X3FV)
LOAD(glProgramUniformMatrix2x3dv, GLPROGRAMUNIFORMMATRIX2X3DV)
LOAD(glProgramUniformMatrix3x2dv, GLPROGRAMUNIFORMMATRIX3X2DV)
LOAD(glProgramUniformMatrix2x4dv, GLPROGRAMUNIFORMMATRIX2X4DV)
LOAD(glProgramUniformMatrix4x2dv, GLPROGRAMUNIFORMMATRIX4X2DV)
LOAD(glProgramUniformMatrix3x4dv, GLPROGRAMUNIFORMMATRIX3X4DV)
LOAD(glProgramUniformMatrix4x3dv, GLPROGRAMUNIFORMMATRIX4X3DV)
LOAD(glValidateProgramPipeline, GLVALIDATEPROGRAMPIPELINE)
LOAD(glGetProgramPipelineInfoLog, GLGETPROGRAMPIPELINEINFOLOG)
LOAD(glVertexAttribLPointer, GLVERTEXATTRIBLPOINTER)
LOAD(glViewportArrayv, GLVIEWPORTARRAYV)
LOAD(glViewportIndexedf, GLVIEWPORTINDEXEDF)
LOAD(glViewportIndexedfv, GLVIEWPORTINDEXEDFV)
LOAD(glScissorArrayv, GLSCISSORARRAYV)
LOAD(glScissorIndexed, GLSCISSORINDEXED)
LOAD(glScissorIndexedv, GLSCISSORINDEXEDV)
LOAD(glDepthRangeArrayv, GLDEPTHRANGEARRAYV)
LOAD(glDepthRangeIndexed, GLDEPTHRANGEINDEXED)
#endif

/* GL 4.2 */

#if GLVERSION >= 420
LOAD(glDrawArraysInstancedBaseInstance, GLDRAWARRAYSINSTANCEDBASEINSTANCE)
LOAD(glDrawElementsInstancedBaseInstance, GLDRAWELEMENTSINSTANCEDBASEINSTANCE)
LOAD(glDrawElementsInstancedBaseVertexBaseInstance, GLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCE)
LOAD(glGetInternalformativ, GLGETINTERNALFORMATIV)
LOAD(glGetActiveAtomicCounterBufferiv, GLGETACTIVEATOMICCOUNTERBUFFERIV)
LOAD(glBindImageTexture, GLBINDIMAGETEXTURE)
LOAD(glMemoryBarrier, GLMEMORYBARRIER)
LOAD(glTexStorage1D, GLTEXSTORAGE1D)
LOAD(glTexStorage2D, GLTEXSTORAGE2D)
LOAD(glTexStorage3D, GLTEXSTORAGE3D)
LOAD(glDrawTransformFeedbackInstanced, GLDRAWTRANSFORMFEEDBACKINSTANCED)
LOAD(glDrawTransformFeedbackStreamInstanced, GLDRAWTRANSFORMFEEDBACKSTREAMINSTANCED)
#endif

/* GL 4.3 */

#if GLVERSION >= 430
LOAD(glClearBufferData, GLCLEARBUFFERDATA)
LOAD(glClearBufferSubData, GLCLEARBUFFERSUBDATA)
LOAD(glDispatchCompute, GLDISPATCHCOMPUTE)
LOAD(glDispatchComputeIndirect, GLDISPATCHCOMPUTEINDIRECT)
LOAD(glCopyImageSubData, GLCOPYIMAGESUBDATA)
LOAD(glFramebufferParameteri, GLFRAMEBUFFERPARAMETERI)
LOAD(glGetFramebufferParameteriv, GLGETFRAMEBUFFERPARAMETERIV)
LOAD(glGetInternalformati64v, GLGETINTERNALFORMATI64V)
LOAD(glInvalidateTexSubImage, GLINVALIDATETEXSUBIMAGE)
LOAD(glInvalidateTexImage, GLINVALIDATETEXIMAGE)
LOAD(glInvalidateBufferSubData, GLINVALIDATEBUFFERSUBDATA)
LOAD(glInvalidateBufferData, GLINVALIDATEBUFFERDATA)
LOAD(glInvalidateFramebuffer, GLINVALIDATEFRAMEBUFFER)
LOAD(glInvalidateSubFramebuffer, GLINVALIDATESUBFRAMEBUFFER)
LOAD(glMultiDrawArraysIndirect, GLMULTIDRAWARRAYSINDIRECT)
LOAD(glMultiDrawElementsIndirect, GLMULTIDRAWELEMENTSINDIRECT)
LOAD(glGetProgramInterfaceiv, GLGETPROGRAMINTERFACEIV)
LOAD(glGetProgramResourceIndex, GLGETPROGRAMRESOURCEINDEX)
LOAD(glGetProgramResourceName, GLGETPROGRAMRESOURCENAME)
LOAD(glGetProgramResourceiv, GLGETPROGRAMRESOURCEIV)
LOAD(glGetProgramResourceLocation, GLGETPROGRAMRESOURCELOCATION)
LOAD(glGetProgramResourceLocationIndex, GLGETPROGRAMRESOURCELOCATIONINDEX)
LOAD(glShaderStorageBlockBinding, GLSHADERSTORAGEBLOCKBINDING)
LOAD(glTexBufferRange, GLTEXBUFFERRANGE)
LOAD(glTexStorage2DMultisample, GLTEXSTORAGE2DMULTISAMPLE)
LOAD(glTexStorage3DMultisample, GLTEXSTORAGE3DMULTISAMPLE)
LOAD(glTextureView, GLTEXTUREVIEW)
LOAD(glBindVertexBuffer, GLBINDVERTEXBUFFER)
LOAD(glVertexAttribFormat, GLVERTEXATTRIBFORMAT)
LOAD(glVertexAttribIFormat, GLVERTEXATTRIBIFORMAT)
LOAD(glVertexAttribLFormat, GLVERTEXATTRIBLFORMAT)
LOAD(glVertexAttribBinding, GLVERTEXATTRIBBINDING)
LOAD(glVertexBindingDivisor, GLVERTEXBINDINGDIVISOR)
LOAD(glDebugMessageControl, GLDEBUGMESSAGECONTROL)
LOAD(glDebugMessageInsert, GLDEBUGMESSAGEINSERT)
LOAD(glDebugMessageCallback, GLDEBUGMESSAGECALLBACK)
LOAD(glGetDebugMessageLog, GLGETDEBUGMESSAGELOG)
LOAD(glPushDebugGroup, GLPUSHDEBUGGROUP)
LOAD(glPopDebugGroup, GLPOPDEBUGGROUP)
LOAD(glObjectLabel, GLOBJECTLABEL)
LOAD(glObjectPtrLabel, GLOBJECTPTRLABEL)
#endif

/* GL 4.4 */

#if GLVERSION >= 440
LOAD(glBufferStorage, GLBUFFERSTORAGE)
LOAD(glClearTexImage, GLCLEARTEXIMAGE)
LOAD(glClearTexSubImage, GLCLEARTEXSUBIMAGE)
LOAD(glBindBuffersBase, GLBINDBUFFERSBASE)
LOAD(glBindBuffersRange, GLBINDBUFFERSRANGE)
LOAD(glBindTextures, GLBINDTEXTURES)
LOAD(glBindSamplers, GLBINDSAMPLERS)
LOAD(glBindImageTextures, GLBINDIMAGETEXTURES)
LOAD(glBindVertexBuffers, GLBINDVERTEXBUFFERS)
#endif

/* GL 4.5 */

#if GLVERSION >= 450
LOAD(glClipControl, GLCLIPCONTROL)
LOAD(glCreateTransformFeedbacks, GLCREATETRANSFORMFEEDBACKS)
LOAD(glTransformFeedbackBufferBase, GLTRANSFORMFEEDBACKBUFFERBASE)
LOAD(glTransformFeedbackBufferRange, GLTRANSFORMFEEDBACKBUFFERRANGE)
LOAD(glGetTransformFeedbackiv, GLGETTRANSFORMFEEDBACKIV)
LOAD(glGetTransformFeedbacki_v, GLGETTRANSFORMFEEDBACKI_V)
LOAD(glGetTransformFeedbacki64_v, GLGETTRANSFORMFEEDBACKI64_V)
LOAD(glCreateBuffers, GLCREATEBUFFERS)
LOAD(glNamedBufferStorage, GLNAMEDBUFFERSTORAGE)
LOAD(glNamedBufferData, GLNAMEDBUFFERDATA)
LOAD(glNamedBufferSubData, GLNAMEDBUFFERSUBDATA)
LOAD(glCopyNamedBufferSubData, GLCOPYNAMEDBUFFERSUBDATA)
LOAD(glClearNamedBufferData, GLCLEARNAMEDBUFFERDATA)
LOAD(glClearNamedBufferSubData, GLCLEARNAMEDBUFFERSUBDATA)
LOAD(glMapNamedBuffer, GLMAPNAMEDBUFFER)
LOAD(glMapNamedBufferRange, GLMAPNAMEDBUFFERRANGE)
LOAD(glUnmapNamedBuffer, GLUNMAPNAMEDBUFFER)
LOAD(glFlushMappedNamedBufferRange, GLFLUSHMAPPEDNAMEDBUFFERRANGE)
LOAD(glGetNamedBufferParameteriv, GLGETNAMEDBUFFERPARAMETERIV)
LOAD(glGetNamedBufferParameteri64v, GLGETNAMEDBUFFERPARAMETERI64V)
LOAD(glGetNamedBufferPointerv, GLGETNAMEDBUFFERPOINTERV)
LOAD(glGetNamedBufferSubData, GLGETNAMEDBUFFERSUBDATA)
LOAD(glCreateFramebuffers, GLCREATEFRAMEBUFFERS)
LOAD(glNamedFramebufferRenderbuffer, GLNAMEDFRAMEBUFFERRENDERBUFFER)
LOAD(glNamedFramebufferParameteri, GLNAMEDFRAMEBUFFERPARAMETERI)
LOAD(glNamedFramebufferTexture, GLNAMEDFRAMEBUFFERTEXTURE)
LOAD(glNamedFramebufferTextureLayer, GLNAMEDFRAMEBUFFERTEXTURELAYER)
LOAD(glNamedFramebufferDrawBuffer, GLNAMEDFRAMEBUFFERDRAWBUFFER)
LOAD(glNamedFramebufferDrawBuffers, GLNAMEDFRAMEBUFFERDRAWBUFFERS)
LOAD(glNamedFramebufferReadBuffer, GLNAMEDFRAMEBUFFERREADBUFFER)
LOAD(glInvalidateNamedFramebufferData, GLINVALIDATENAMEDFRAMEBUFFERDATA)
LOAD(glInvalidateNamedFramebufferSubData, GLINVALIDATENAMEDFRAMEBUFFERSUBDATA)
LOAD(glClearNamedFramebufferiv, GLCLEARNAMEDFRAMEBUFFERIV)
LOAD(glClearNamedFramebufferuiv, GLCLEARNAMEDFRAMEBUFFERUIV)
LOAD(glClearNamedFramebufferfv, GLCLEARNAMEDFRAMEBUFFERFV)
LOAD(glClearNamedFramebufferfi, GLCLEARNAMEDFRAMEBUFFERFI)
LOAD(glBlitNamedFramebuffer, GLBLITNAMEDFRAMEBUFFER)
LOAD(glCheckNamedFramebufferStatus, GLCHECKNAMEDFRAMEBUFFERSTATUS)
LOAD(glGetNamedFramebufferParameteriv, GLGETNAMEDFRAMEBUFFERPARAMETERIV)
LOAD(glGetNamedFramebufferAttachmentParameteriv, GLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIV)
LOAD(glCreateRenderbuffers, GLCREATERENDERBUFFERS)
LOAD(glNamedRenderbufferStorage, GLNAMEDRENDERBUFFERSTORAGE)
LOAD(glNamedRenderbufferStorageMultisample, GLNAMEDRENDERBUFFERSTORAGEMULTISAMPLE)
LOAD(glGetNamedRenderbufferParameteriv, GLGETNAMEDRENDERBUFFERPARAMETERIV)
LOAD(glCreateTextures, GLCREATETEXTURES)
LOAD(glTextureBuffer, GLTEXTUREBUFFER)
LOAD(glTextureBufferRange, GLTEXTUREBUFFERRANGE)
LOAD(glTextureStorage1D, GLTEXTURESTORAGE1D)
LOAD(glTextureStorage2D, GLTEXTURESTORAGE2D)
LOAD(glTextureStorage3D, GLTEXTURESTORAGE3D)
LOAD(glTextureStorage2DMultisample, GLTEXTURESTORAGE2DMULTISAMPLE)
LOAD(glTextureStorage3DMultisample, GLTEXTURESTORAGE3DMULTISAMPLE)
LOAD(glTextureSubImage1D, GLTEXTURESUBIMAGE1D)
LOAD(glTextureSubImage2D, GLTEXTURESUBIMAGE2D)
LOAD(glTextureSubImage3D, GLTEXTURESUBIMAGE3D)
LOAD(glCompressedTextureSubImage1D, GLCOMPRESSEDTEXTURESUBIMAGE1D)
LOAD(glCompressedTextureSubImage2D, GLCOMPRESSEDTEXTURESUBIMAGE2D)
LOAD(glCompressedTextureSubImage3D, GLCOMPRESSEDTEXTURESUBIMAGE3D)
LOAD(glCopyTextureSubImage1D, GLCOPYTEXTURESUBIMAGE1D)
LOAD(glCopyTextureSubImage2D, GLCOPYTEXTURESUBIMAGE2D)
LOAD(glCopyTextureSubImage3D, GLCOPYTEXTURESUBIMAGE3D)
LOAD(glTextureParameterf, GLTEXTUREPARAMETERF)
LOAD(glTextureParameterfv, GLTEXTUREPARAMETERFV)
LOAD(glTextureParameteri, GLTEXTUREPARAMETERI)
LOAD(glTextureParameterIiv, GLTEXTUREPARAMETERIIV)
LOAD(glTextureParameterIuiv, GLTEXTUREPARAMETERIUIV)
LOAD(glTextureParameteriv, GLTEXTUREPARAMETERIV)
LOAD(glGenerateTextureMipmap, GLGENERATETEXTUREMIPMAP)
LOAD(glBindTextureUnit, GLBINDTEXTUREUNIT)
LOAD(glGetTextureImage, GLGETTEXTUREIMAGE)
LOAD(glGetCompressedTextureImage, GLGETCOMPRESSEDTEXTUREIMAGE)
LOAD(glGetTextureLevelParameterfv, GLGETTEXTURELEVELPARAMETERFV)
LOAD(glGetTextureLevelParameteriv, GLGETTEXTURELEVELPARAMETERIV)
LOAD(glGetTextureParameterfv, GLGETTEXTUREPARAMETERFV)
LOAD(glGetTextureParameterIiv, GLGETTEXTUREPARAMETERIIV)
LOAD(glGetTextureParameterIuiv, GLGETTEXTUREPARAMETERIUIV)
LOAD(glGetTextureParameteriv, GLGETTEXTUREPARAMETERIV)
LOAD(glCreateVertexArrays, GLCREATEVERTEXARRAYS)
LOAD(glDisableVertexArrayAttrib, GLDISABLEVERTEXARRAYATTRIB)
LOAD(glEnableVertexArrayAttrib, GLENABLEVERTEXARRAYATTRIB)
LOAD(glVertexArrayElementBuffer, GLVERTEXARRAYELEMENTBUFFER)
LOAD(glVertexArrayVertexBuffer, GLVERTEXARRAYVERTEXBUFFER)
LOAD(glVertexArrayVertexBuffers, GLVERTEXARRAYVERTEXBUFFERS)
LOAD(glVertexArrayAttribBinding, GLVERTEXARRAYATTRIBBINDING)
LOAD(glVertexArrayAttribFormat, GLVERTEXARRAYATTRIBFORMAT)
LOAD(glVertexArrayAttribIFormat, GLVERTEXARRAYATTRIBIFORMAT)
LOAD(glVertexArrayAttribLFormat, GLVERTEXARRAYATTRIBLFORMAT)
LOAD(glVertexArrayBindingDivisor, GLVERTEXARRAYBINDINGDIVISOR)
LOAD(glGetVertexArrayiv, GLGETVERTEXARRAYIV)
LOAD(glGetVertexArrayIndexediv, GLGETVERTEXARRAYINDEXEDIV)
LOAD(glGetVertexArrayIndexed64iv, GLGETVERTEXARRAYINDEXED64IV)
LOAD(glCreateSamplers, GLCREATESAMPLERS)
LOAD(glCreateProgramPipelines, GLCREATEPROGRAMPIPELINES)
LOAD(glCreateQueries, GLCREATEQUERIES)
LOAD(glGetQueryBufferObjecti64v, GLGETQUERYBUFFEROBJECTI64V)
LOAD(glGetQueryBufferObjectiv, GLGETQUERYBUFFEROBJECTIV)
LOAD(glGetQueryBufferObjectui64v, GLGETQUERYBUFFEROBJECTUI64V)
LOAD(glGetQueryBufferObjectuiv, GLGETQUERYBUFFEROBJECTUIV)
LOAD(glMemoryBarrierByRegion, GLMEMORYBARRIERBYREGION)
LOAD(glGetTextureSubImage, GLGETTEXTURESUBIMAGE)
LOAD(glGetCompressedTextureSubImage, GLGETCOMPRESSEDTEXTURESUBIMAGE)
LOAD(glGetGraphicsResetStatus, GLGETGRAPHICSRESETSTATUS)
LOAD(glGetnCompressedTexImage, GLGETNCOMPRESSEDTEXIMAGE)
LOAD(glGetnTexImage, GLGETNTEXIMAGE)
LOAD(glGetnUniformdv, GLGETNUNIFORMDV)
LOAD(glGetnUniformfv, GLGETNUNIFORMFV)
LOAD(glGetnUniformiv, GLGETNUNIFORMIV)
LOAD(glGetnUniformuiv, GLGETNUNIFORMUIV)
LOAD(glReadnPixels, GLREADNPIXELS)
LOAD(glGetnMapdv, GLGETNMAPDV)
LOAD(glGetnMapfv, GLGETNMAPFV)
LOAD(glGetnMapiv, GLGETNMAPIV)
LOAD(glGetnPixelMapfv, GLGETNPIXELMAPFV)
LOAD(glGetnPixelMapuiv, GLGETNPIXELMAPUIV)
LOAD(glGetnPixelMapusv, GLGETNPIXELMAPUSV)
LOAD(glGetnPolygonStipple, GLGETNPOLYGONSTIPPLE)
LOAD(glGetnColorTable, GLGETNCOLORTABLE)
LOAD(glGetnConvolutionFilter, GLGETNCONVOLUTIONFILTER)
LOAD(glGetnSeparableFilter, GLGETNSEPARABLEFILTER)
LOAD(glGetnHistogram, GLGETNHISTOGRAM)
LOAD(glGetnMinmax, GLGETNMINMAX)
LOAD(glTextureBarrier, GLTEXTUREBARRIER)
#endif

#if GLVERSION < 410
REQUIRE(ARB_separate_shader_objects)
/*LOAD(glUseProgramStages, GLUSEPROGRAMSTAGES)*/
/*LOAD(glActiveShaderProgram, GLACTIVESHADERPROGRAM)*/
/*LOAD(glCreateShaderProgramv, GLCREATESHADERPROGRAMV)*/
/*LOAD(glBindProgramPipeline, GLBINDPROGRAMPIPELINE)*/
/*LOAD(glDeleteProgramPipelines, GLDELETEPROGRAMPIPELINES)*/
/*LOAD(glGenProgramPipelines, GLGENPROGRAMPIPELINES)*/
/*LOAD(glIsProgramPipeline, GLISPROGRAMPIPELINE)*/
/*LOAD(glGetProgramPipelineiv, GLGETPROGRAMPIPELINEIV)*/
/*LOAD(glProgramUniform1i, GLPROGRAMUNIFORM1I)*/
/*LOAD(glProgramUniform1iv, GLPROGRAMUNIFORM1IV)*/
/*LOAD(glProgramUniform1f, GLPROGRAMUNIFORM1F)*/
/*LOAD(glProgramUniform1fv, GLPROGRAMUNIFORM1FV)*/
/*LOAD(glProgramUniform1d, GLPROGRAMUNIFORM1D)*/
/*LOAD(glProgramUniform1dv, GLPROGRAMUNIFORM1DV)*/
/*LOAD(glProgramUniform1ui, GLPROGRAMUNIFORM1UI)*/
/*LOAD(glProgramUniform1uiv, GLPROGRAMUNIFORM1UIV)*/
/*LOAD(glProgramUniform2i, GLPROGRAMUNIFORM2I)*/
/*LOAD(glProgramUniform2iv, GLPROGRAMUNIFORM2IV)*/
/*LOAD(glProgramUniform2f, GLPROGRAMUNIFORM2F)*/
/*LOAD(glProgramUniform2fv, GLPROGRAMUNIFORM2FV)*/
/*LOAD(glProgramUniform2d, GLPROGRAMUNIFORM2D)*/
/*LOAD(glProgramUniform2dv, GLPROGRAMUNIFORM2DV)*/
/*LOAD(glProgramUniform2ui, GLPROGRAMUNIFORM2UI)*/
/*LOAD(glProgramUniform2uiv, GLPROGRAMUNIFORM2UIV)*/
/*LOAD(glProgramUniform3i, GLPROGRAMUNIFORM3I)*/
/*LOAD(glProgramUniform3iv, GLPROGRAMUNIFORM3IV)*/
/*LOAD(glProgramUniform3f, GLPROGRAMUNIFORM3F)*/
/*LOAD(glProgramUniform3fv, GLPROGRAMUNIFORM3FV)*/
/*LOAD(glProgramUniform3d, GLPROGRAMUNIFORM3D)*/
/*LOAD(glProgramUniform3dv, GLPROGRAMUNIFORM3DV)*/
/*LOAD(glProgramUniform3ui, GLPROGRAMUNIFORM3UI)*/
/*LOAD(glProgramUniform3uiv, GLPROGRAMUNIFORM3UIV)*/
/*LOAD(glProgramUniform4i, GLPROGRAMUNIFORM4I)*/
/*LOAD(glProgramUniform4iv, GLPROGRAMUNIFORM4IV)*/
/*LOAD(glProgramUniform4f, GLPROGRAMUNIFORM4F)*/
/*LOAD(glProgramUniform4fv, GLPROGRAMUNIFORM4FV)*/
/*LOAD(glProgramUniform4d, GLPROGRAMUNIFORM4D)*/
/*LOAD(glProgramUniform4dv, GLPROGRAMUNIFORM4DV)*/
/*LOAD(glProgramUniform4ui, GLPROGRAMUNIFORM4UI)*/
/*LOAD(glProgramUniform4uiv, GLPROGRAMUNIFORM4UIV)*/
/*LOAD(glProgramUniformMatrix2fv, GLPROGRAMUNIFORMMATRIX2FV)*/
/*LOAD(glProgramUniformMatrix3fv, GLPROGRAMUNIFORMMATRIX3FV)*/
/*LOAD(glProgramUniformMatrix4fv, GLPROGRAMUNIFORMMATRIX4FV)*/
/*LOAD(glProgramUniformMatrix2dv, GLPROGRAMUNIFORMMATRIX2DV)*/
/*LOAD(glProgramUniformMatrix3dv, GLPROGRAMUNIFORMMATRIX3DV)*/
/*LOAD(glProgramUniformMatrix4dv, GLPROGRAMUNIFORMMATRIX4DV)*/
/*LOAD(glProgramUniformMatrix2x3fv, GLPROGRAMUNIFORMMATRIX2X3FV)*/
/*LOAD(glProgramUniformMatrix3x2fv, GLPROGRAMUNIFORMMATRIX3X2FV)*/
/*LOAD(glProgramUniformMatrix2x4fv, GLPROGRAMUNIFORMMATRIX2X4FV)*/
/*LOAD(glProgramUniformMatrix4x2fv, GLPROGRAMUNIFORMMATRIX4X2FV)*/
/*LOAD(glProgramUniformMatrix3x4fv, GLPROGRAMUNIFORMMATRIX3X4FV)*/
/*LOAD(glProgramUniformMatrix4x3fv, GLPROGRAMUNIFORMMATRIX4X3FV)*/
/*LOAD(glProgramUniformMatrix2x3dv, GLPROGRAMUNIFORMMATRIX2X3DV)*/
/*LOAD(glProgramUniformMatrix3x2dv, GLPROGRAMUNIFORMMATRIX3X2DV)*/
/*LOAD(glProgramUniformMatrix2x4dv, GLPROGRAMUNIFORMMATRIX2X4DV)*/
/*LOAD(glProgramUniformMatrix4x2dv, GLPROGRAMUNIFORMMATRIX4X2DV)*/
/*LOAD(glProgramUniformMatrix3x4dv, GLPROGRAMUNIFORMMATRIX3X4DV)*/
/*LOAD(glProgramUniformMatrix4x3dv, GLPROGRAMUNIFORMMATRIX4X3DV)*/
/*LOAD(glValidateProgramPipeline, GLVALIDATEPROGRAMPIPELINE)*/
/*LOAD(glGetProgramPipelineInfoLog, GLGETPROGRAMPIPELINEINFOLOG)*/
/*END*/
#endif

#if GLVERSION < 420
REQUIRE(ARB_shading_language_420pack)
#endif

#if (GLVERSION < 430) // && !defined(GL_DSA)
OPTIONAL(ARB_invalidate_subdata)
LOAD(glInvalidateFramebuffer, GLINVALIDATEFRAMEBUFFER)
END
#endif

/*CHECK(EXT_texture_buffer_object)*/
/*CHECK(EXT_geometry_shader4)*/
/*CHECK(EXT_texture_integer)*/
/*CHECK(EXT_gpu_shader4)*/
/*CHECK(EXT_gpu_program_parameters)*/
/*CHECK(EXT_vertex_attrib_64bit)*/
/*CHECK(NV_gpu_program4)*/
/*CHECK(NV_framebuffer_multisample_coverage)*/
/*CHECK(NV_explicit_multisample)*/
/*CHECK(ARB_vertex_attrib_binding)*/
/*CHECK(ARB_clear_buffer_object)*/
/*CHECK(ARB_framebuffer_no_attachments)*/
/*CHECK(ARB_texture_buffer_range)*/
/*CHECK(ARB_texture_storage)*/
/*CHECK(ARB_texture_storage_multisample)*/
/*CHECK(ARB_sparse_texture)*/
/*CHECK(ARB_instanced_arrays)*/

/*REQUIRE(EXT_texture_filter_anisotropic)*/

#if GLVERSION < 440
/*OPTIONAL(ARB_buffer_storage)*/
/*LOAD(glBufferStorage, GLBUFFERSTORAGE)*/
/*END*/
#endif

/*
OPTIONAL(EXT_direct_state_access)
LOAD(glMatrixLoadfEXT, GLMATRIXLOADFEXT)
LOAD(glMatrixLoaddEXT, GLMATRIXLOADDEXT)
LOAD(glMatrixMultfEXT, GLMATRIXMULTFEXT)
LOAD(glMatrixMultdEXT, GLMATRIXMULTDEXT)
LOAD(glMatrixLoadIdentityEXT, GLMATRIXLOADIDENTITYEXT)
LOAD(glMatrixRotatefEXT, GLMATRIXROTATEFEXT)
LOAD(glMatrixRotatedEXT, GLMATRIXROTATEDEXT)
LOAD(glMatrixScalefEXT, GLMATRIXSCALEFEXT)
LOAD(glMatrixScaledEXT, GLMATRIXSCALEDEXT)
LOAD(glMatrixTranslatefEXT, GLMATRIXTRANSLATEFEXT)
LOAD(glMatrixTranslatedEXT, GLMATRIXTRANSLATEDEXT)
LOAD(glMatrixFrustumEXT, GLMATRIXFRUSTUMEXT)
LOAD(glMatrixOrthoEXT, GLMATRIXORTHOEXT)
LOAD(glMatrixPopEXT, GLMATRIXPOPEXT)
LOAD(glMatrixPushEXT, GLMATRIXPUSHEXT)
LOAD(glClientAttribDefaultEXT, GLCLIENTATTRIBDEFAULTEXT)
LOAD(glPushClientAttribDefaultEXT, GLPUSHCLIENTATTRIBDEFAULTEXT)
LOAD(glTextureParameterfEXT, GLTEXTUREPARAMETERFEXT)
LOAD(glTextureParameterfvEXT, GLTEXTUREPARAMETERFVEXT)
LOAD(glTextureParameteriEXT, GLTEXTUREPARAMETERIEXT)
LOAD(glTextureParameterivEXT, GLTEXTUREPARAMETERIVEXT)
LOAD(glTextureImage1DEXT, GLTEXTUREIMAGE1DEXT)
LOAD(glTextureImage2DEXT, GLTEXTUREIMAGE2DEXT)
LOAD(glTextureSubImage1DEXT, GLTEXTURESUBIMAGE1DEXT)
LOAD(glTextureSubImage2DEXT, GLTEXTURESUBIMAGE2DEXT)
LOAD(glCopyTextureImage1DEXT, GLCOPYTEXTUREIMAGE1DEXT)
LOAD(glCopyTextureImage2DEXT, GLCOPYTEXTUREIMAGE2DEXT)
LOAD(glCopyTextureSubImage1DEXT, GLCOPYTEXTURESUBIMAGE1DEXT)
LOAD(glCopyTextureSubImage2DEXT, GLCOPYTEXTURESUBIMAGE2DEXT)
LOAD(glGetTextureImageEXT, GLGETTEXTUREIMAGEEXT)
LOAD(glGetTextureParameterfvEXT, GLGETTEXTUREPARAMETERFVEXT)
LOAD(glGetTextureParameterivEXT, GLGETTEXTUREPARAMETERIVEXT)
LOAD(glGetTextureLevelParameterfvEXT, GLGETTEXTURELEVELPARAMETERFVEXT)
LOAD(glGetTextureLevelParameterivEXT, GLGETTEXTURELEVELPARAMETERIVEXT)
LOAD(glTextureImage3DEXT, GLTEXTUREIMAGE3DEXT)
LOAD(glTextureSubImage3DEXT, GLTEXTURESUBIMAGE3DEXT)
LOAD(glCopyTextureSubImage3DEXT, GLCOPYTEXTURESUBIMAGE3DEXT)
LOAD(glBindMultiTextureEXT, GLBINDMULTITEXTUREEXT)
LOAD(glMultiTexCoordPointerEXT, GLMULTITEXCOORDPOINTEREXT)
LOAD(glMultiTexEnvfEXT, GLMULTITEXENVFEXT)
LOAD(glMultiTexEnvfvEXT, GLMULTITEXENVFVEXT)
LOAD(glMultiTexEnviEXT, GLMULTITEXENVIEXT)
LOAD(glMultiTexEnvivEXT, GLMULTITEXENVIVEXT)
LOAD(glMultiTexGendEXT, GLMULTITEXGENDEXT)
LOAD(glMultiTexGendvEXT, GLMULTITEXGENDVEXT)
LOAD(glMultiTexGenfEXT, GLMULTITEXGENFEXT)
LOAD(glMultiTexGenfvEXT, GLMULTITEXGENFVEXT)
LOAD(glMultiTexGeniEXT, GLMULTITEXGENIEXT)
LOAD(glMultiTexGenivEXT, GLMULTITEXGENIVEXT)
LOAD(glGetMultiTexEnvfvEXT, GLGETMULTITEXENVFVEXT)
LOAD(glGetMultiTexEnvivEXT, GLGETMULTITEXENVIVEXT)
LOAD(glGetMultiTexGendvEXT, GLGETMULTITEXGENDVEXT)
LOAD(glGetMultiTexGenfvEXT, GLGETMULTITEXGENFVEXT)
LOAD(glGetMultiTexGenivEXT, GLGETMULTITEXGENIVEXT)
LOAD(glMultiTexParameteriEXT, GLMULTITEXPARAMETERIEXT)
LOAD(glMultiTexParameterivEXT, GLMULTITEXPARAMETERIVEXT)
LOAD(glMultiTexParameterfEXT, GLMULTITEXPARAMETERFEXT)
LOAD(glMultiTexParameterfvEXT, GLMULTITEXPARAMETERFVEXT)
LOAD(glMultiTexImage1DEXT, GLMULTITEXIMAGE1DEXT)
LOAD(glMultiTexImage2DEXT, GLMULTITEXIMAGE2DEXT)
LOAD(glMultiTexSubImage1DEXT, GLMULTITEXSUBIMAGE1DEXT)
LOAD(glMultiTexSubImage2DEXT, GLMULTITEXSUBIMAGE2DEXT)
LOAD(glCopyMultiTexImage1DEXT, GLCOPYMULTITEXIMAGE1DEXT)
LOAD(glCopyMultiTexImage2DEXT, GLCOPYMULTITEXIMAGE2DEXT)
LOAD(glCopyMultiTexSubImage1DEXT, GLCOPYMULTITEXSUBIMAGE1DEXT)
LOAD(glCopyMultiTexSubImage2DEXT, GLCOPYMULTITEXSUBIMAGE2DEXT)
LOAD(glGetMultiTexImageEXT, GLGETMULTITEXIMAGEEXT)
LOAD(glGetMultiTexParameterfvEXT, GLGETMULTITEXPARAMETERFVEXT)
LOAD(glGetMultiTexParameterivEXT, GLGETMULTITEXPARAMETERIVEXT)
LOAD(glGetMultiTexLevelParameterfvEXT, GLGETMULTITEXLEVELPARAMETERFVEXT)
LOAD(glGetMultiTexLevelParameterivEXT, GLGETMULTITEXLEVELPARAMETERIVEXT)
LOAD(glMultiTexImage3DEXT, GLMULTITEXIMAGE3DEXT)
LOAD(glMultiTexSubImage3DEXT, GLMULTITEXSUBIMAGE3DEXT)
LOAD(glCopyMultiTexSubImage3DEXT, GLCOPYMULTITEXSUBIMAGE3DEXT)
LOAD(glEnableClientStateIndexedEXT, GLENABLECLIENTSTATEINDEXEDEXT)
LOAD(glDisableClientStateIndexedEXT, GLDISABLECLIENTSTATEINDEXEDEXT)
LOAD(glGetFloatIndexedvEXT, GLGETFLOATINDEXEDVEXT)
LOAD(glGetDoubleIndexedvEXT, GLGETDOUBLEINDEXEDVEXT)
LOAD(glGetPointerIndexedvEXT, GLGETPOINTERINDEXEDVEXT)
LOAD(glEnableIndexedEXT, GLENABLEINDEXEDEXT)
LOAD(glDisableIndexedEXT, GLDISABLEINDEXEDEXT)
LOAD(glIsEnabledIndexedEXT, GLISENABLEDINDEXEDEXT)
LOAD(glGetIntegerIndexedvEXT, GLGETINTEGERINDEXEDVEXT)
LOAD(glGetBooleanIndexedvEXT, GLGETBOOLEANINDEXEDVEXT)
LOAD(glCompressedTextureImage3DEXT, GLCOMPRESSEDTEXTUREIMAGE3DEXT)
LOAD(glCompressedTextureImage2DEXT, GLCOMPRESSEDTEXTUREIMAGE2DEXT)
LOAD(glCompressedTextureImage1DEXT, GLCOMPRESSEDTEXTUREIMAGE1DEXT)
LOAD(glCompressedTextureSubImage3DEXT, GLCOMPRESSEDTEXTURESUBIMAGE3DEXT)
LOAD(glCompressedTextureSubImage2DEXT, GLCOMPRESSEDTEXTURESUBIMAGE2DEXT)
LOAD(glCompressedTextureSubImage1DEXT, GLCOMPRESSEDTEXTURESUBIMAGE1DEXT)
LOAD(glGetCompressedTextureImageEXT, GLGETCOMPRESSEDTEXTUREIMAGEEXT)
LOAD(glCompressedMultiTexImage3DEXT, GLCOMPRESSEDMULTITEXIMAGE3DEXT)
LOAD(glCompressedMultiTexImage2DEXT, GLCOMPRESSEDMULTITEXIMAGE2DEXT)
LOAD(glCompressedMultiTexImage1DEXT, GLCOMPRESSEDMULTITEXIMAGE1DEXT)
LOAD(glCompressedMultiTexSubImage3DEXT, GLCOMPRESSEDMULTITEXSUBIMAGE3DEXT)
LOAD(glCompressedMultiTexSubImage2DEXT, GLCOMPRESSEDMULTITEXSUBIMAGE2DEXT)
LOAD(glCompressedMultiTexSubImage1DEXT, GLCOMPRESSEDMULTITEXSUBIMAGE1DEXT)
LOAD(glGetCompressedMultiTexImageEXT, GLGETCOMPRESSEDMULTITEXIMAGEEXT)
LOAD(glMatrixLoadTransposefEXT, GLMATRIXLOADTRANSPOSEFEXT)
LOAD(glMatrixLoadTransposedEXT, GLMATRIXLOADTRANSPOSEDEXT)
LOAD(glMatrixMultTransposefEXT, GLMATRIXMULTTRANSPOSEFEXT)
LOAD(glMatrixMultTransposedEXT, GLMATRIXMULTTRANSPOSEDEXT)
LOAD(glNamedBufferDataEXT, GLNAMEDBUFFERDATAEXT)
LOAD(glNamedBufferSubDataEXT, GLNAMEDBUFFERSUBDATAEXT)
LOAD(glMapNamedBufferEXT, GLMAPNAMEDBUFFEREXT)
LOAD(glUnmapNamedBufferEXT, GLUNMAPNAMEDBUFFEREXT)
LOAD(glGetNamedBufferParameterivEXT, GLGETNAMEDBUFFERPARAMETERIVEXT)
LOAD(glGetNamedBufferPointervEXT, GLGETNAMEDBUFFERPOINTERVEXT)
LOAD(glGetNamedBufferSubDataEXT, GLGETNAMEDBUFFERSUBDATAEXT)
LOAD(glProgramUniform1fEXT, GLPROGRAMUNIFORM1FEXT)
LOAD(glProgramUniform2fEXT, GLPROGRAMUNIFORM2FEXT)
LOAD(glProgramUniform3fEXT, GLPROGRAMUNIFORM3FEXT)
LOAD(glProgramUniform4fEXT, GLPROGRAMUNIFORM4FEXT)
LOAD(glProgramUniform1iEXT, GLPROGRAMUNIFORM1IEXT)
LOAD(glProgramUniform2iEXT, GLPROGRAMUNIFORM2IEXT)
LOAD(glProgramUniform3iEXT, GLPROGRAMUNIFORM3IEXT)
LOAD(glProgramUniform4iEXT, GLPROGRAMUNIFORM4IEXT)
LOAD(glProgramUniform1fvEXT, GLPROGRAMUNIFORM1FVEXT)
LOAD(glProgramUniform2fvEXT, GLPROGRAMUNIFORM2FVEXT)
LOAD(glProgramUniform3fvEXT, GLPROGRAMUNIFORM3FVEXT)
LOAD(glProgramUniform4fvEXT, GLPROGRAMUNIFORM4FVEXT)
LOAD(glProgramUniform1ivEXT, GLPROGRAMUNIFORM1IVEXT)
LOAD(glProgramUniform2ivEXT, GLPROGRAMUNIFORM2IVEXT)
LOAD(glProgramUniform3ivEXT, GLPROGRAMUNIFORM3IVEXT)
LOAD(glProgramUniform4ivEXT, GLPROGRAMUNIFORM4IVEXT)
LOAD(glProgramUniformMatrix2fvEXT, GLPROGRAMUNIFORMMATRIX2FVEXT)
LOAD(glProgramUniformMatrix3fvEXT, GLPROGRAMUNIFORMMATRIX3FVEXT)
LOAD(glProgramUniformMatrix4fvEXT, GLPROGRAMUNIFORMMATRIX4FVEXT)
LOAD(glProgramUniformMatrix2x3fvEXT, GLPROGRAMUNIFORMMATRIX2X3FVEXT)
LOAD(glProgramUniformMatrix3x2fvEXT, GLPROGRAMUNIFORMMATRIX3X2FVEXT)
LOAD(glProgramUniformMatrix2x4fvEXT, GLPROGRAMUNIFORMMATRIX2X4FVEXT)
LOAD(glProgramUniformMatrix4x2fvEXT, GLPROGRAMUNIFORMMATRIX4X2FVEXT)
LOAD(glProgramUniformMatrix3x4fvEXT, GLPROGRAMUNIFORMMATRIX3X4FVEXT)
LOAD(glProgramUniformMatrix4x3fvEXT, GLPROGRAMUNIFORMMATRIX4X3FVEXT)
IF(EXT_texture_buffer_object)
	LOAD(glTextureBufferEXT, GLTEXTUREBUFFEREXT)
	LOAD(glMultiTexBufferEXT, GLMULTITEXBUFFEREXT)
ENDIF
IF(EXT_texture_integer)
	LOAD(glTextureParameterIivEXT, GLTEXTUREPARAMETERIIVEXT)
	LOAD(glTextureParameterIuivEXT, GLTEXTUREPARAMETERIUIVEXT)
	LOAD(glGetTextureParameterIivEXT, GLGETTEXTUREPARAMETERIIVEXT)
	LOAD(glGetTextureParameterIuivEXT, GLGETTEXTUREPARAMETERIUIVEXT)
	LOAD(glMultiTexParameterIivEXT, GLMULTITEXPARAMETERIIVEXT)
	LOAD(glMultiTexParameterIuivEXT, GLMULTITEXPARAMETERIUIVEXT)
	LOAD(glGetMultiTexParameterIivEXT, GLGETMULTITEXPARAMETERIIVEXT)
	LOAD(glGetMultiTexParameterIuivEXT, GLGETMULTITEXPARAMETERIUIVEXT)
ENDIF
IF(EXT_gpu_shader4)
	LOAD(glProgramUniform1uiEXT, GLPROGRAMUNIFORM1UIEXT)
	LOAD(glProgramUniform2uiEXT, GLPROGRAMUNIFORM2UIEXT)
	LOAD(glProgramUniform3uiEXT, GLPROGRAMUNIFORM3UIEXT)
	LOAD(glProgramUniform4uiEXT, GLPROGRAMUNIFORM4UIEXT)
	LOAD(glProgramUniform1uivEXT, GLPROGRAMUNIFORM1UIVEXT)
	LOAD(glProgramUniform2uivEXT, GLPROGRAMUNIFORM2UIVEXT)
	LOAD(glProgramUniform3uivEXT, GLPROGRAMUNIFORM3UIVEXT)
	LOAD(glProgramUniform4uivEXT, GLPROGRAMUNIFORM4UIVEXT)
ENDIF
IF(EXT_gpu_program_parameters)
LOAD(glNamedProgramLocalParameters4fvEXT, GLNAMEDPROGRAMLOCALPARAMETERS4FVEXT)
ENDIF
IF(NV_gpu_program4)
	LOAD(glNamedProgramLocalParameterI4iEXT, GLNAMEDPROGRAMLOCALPARAMETERI4IEXT)
	LOAD(glNamedProgramLocalParameterI4ivEXT, GLNAMEDPROGRAMLOCALPARAMETERI4IVEXT)
	LOAD(glNamedProgramLocalParametersI4ivEXT, GLNAMEDPROGRAMLOCALPARAMETERSI4IVEXT)
	LOAD(glNamedProgramLocalParameterI4uiEXT, GLNAMEDPROGRAMLOCALPARAMETERI4UIEXT)
	LOAD(glNamedProgramLocalParameterI4uivEXT, GLNAMEDPROGRAMLOCALPARAMETERI4UIVEXT)
	LOAD(glNamedProgramLocalParametersI4uivEXT, GLNAMEDPROGRAMLOCALPARAMETERSI4UIVEXT)
	LOAD(glGetNamedProgramLocalParameterIivEXT, GLGETNAMEDPROGRAMLOCALPARAMETERIIVEXT)
	LOAD(glGetNamedProgramLocalParameterIuivEXT, GLGETNAMEDPROGRAMLOCALPARAMETERIUIVEXT)
ENDIF
LOAD(glEnableClientStateiEXT, GLENABLECLIENTSTATEIEXT)
LOAD(glDisableClientStateiEXT, GLDISABLECLIENTSTATEIEXT)
LOAD(glGetFloati_vEXT, GLGETFLOATI_VEXT)
LOAD(glGetDoublei_vEXT, GLGETDOUBLEI_VEXT)
LOAD(glGetPointeri_vEXT, GLGETPOINTERI_VEXT)
LOAD(glNamedProgramStringEXT, GLNAMEDPROGRAMSTRINGEXT)
LOAD(glNamedProgramLocalParameter4dEXT, GLNAMEDPROGRAMLOCALPARAMETER4DEXT)
LOAD(glNamedProgramLocalParameter4dvEXT, GLNAMEDPROGRAMLOCALPARAMETER4DVEXT)
LOAD(glNamedProgramLocalParameter4fEXT, GLNAMEDPROGRAMLOCALPARAMETER4FEXT)
LOAD(glNamedProgramLocalParameter4fvEXT, GLNAMEDPROGRAMLOCALPARAMETER4FVEXT)
LOAD(glGetNamedProgramLocalParameterdvEXT, GLGETNAMEDPROGRAMLOCALPARAMETERDVEXT)
LOAD(glGetNamedProgramLocalParameterfvEXT, GLGETNAMEDPROGRAMLOCALPARAMETERFVEXT)
LOAD(glGetNamedProgramivEXT, GLGETNAMEDPROGRAMIVEXT)
LOAD(glGetNamedProgramStringEXT, GLGETNAMEDPROGRAMSTRINGEXT)
LOAD(glNamedRenderbufferStorageEXT, GLNAMEDRENDERBUFFERSTORAGEEXT)
LOAD(glGetNamedRenderbufferParameterivEXT, GLGETNAMEDRENDERBUFFERPARAMETERIVEXT)
LOAD(glNamedRenderbufferStorageMultisampleEXT, GLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEEXT)
LOAD(glNamedRenderbufferStorageMultisampleCoverageEXT, GLNAMEDRENDERBUFFERSTORAGEMULTISAMPLECOVERAGEEXT)
LOAD(glCheckNamedFramebufferStatusEXT, GLCHECKNAMEDFRAMEBUFFERSTATUSEXT)
LOAD(glNamedFramebufferTexture1DEXT, GLNAMEDFRAMEBUFFERTEXTURE1DEXT)
LOAD(glNamedFramebufferTexture2DEXT, GLNAMEDFRAMEBUFFERTEXTURE2DEXT)
LOAD(glNamedFramebufferTexture3DEXT, GLNAMEDFRAMEBUFFERTEXTURE3DEXT)
LOAD(glNamedFramebufferRenderbufferEXT, GLNAMEDFRAMEBUFFERRENDERBUFFEREXT)
LOAD(glGetNamedFramebufferAttachmentParameterivEXT, GLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVEXT)
LOAD(glGenerateTextureMipmapEXT, GLGENERATETEXTUREMIPMAPEXT)
LOAD(glGenerateMultiTexMipmapEXT, GLGENERATEMULTITEXMIPMAPEXT)
LOAD(glFramebufferDrawBufferEXT, GLFRAMEBUFFERDRAWBUFFEREXT)
LOAD(glFramebufferDrawBuffersEXT, GLFRAMEBUFFERDRAWBUFFERSEXT)
LOAD(glFramebufferReadBufferEXT, GLFRAMEBUFFERREADBUFFEREXT)
LOAD(glGetFramebufferParameterivEXT, GLGETFRAMEBUFFERPARAMETERIVEXT)
LOAD(glNamedCopyBufferSubDataEXT, GLNAMEDCOPYBUFFERSUBDATAEXT)
IF(!(EXT_geometry_shader4 || NV_gpu_program4))
	LOAD(glNamedFramebufferTextureEXT, GLNAMEDFRAMEBUFFERTEXTUREEXT)
	LOAD(glNamedFramebufferTextureLayerEXT, GLNAMEDFRAMEBUFFERTEXTURELAYEREXT)
	LOAD(glNamedFramebufferTextureFaceEXT, GLNAMEDFRAMEBUFFERTEXTUREFACEEXT)
ENDIF
IF(NV_explicit_multisample)
	LOAD(glTextureRenderbufferEXT, GLTEXTURERENDERBUFFEREXT)
	LOAD(glMultiTexRenderbufferEXT, GLMULTITEXRENDERBUFFEREXT)
ENDIF
	LOAD(glVertexArrayVertexOffsetEXT, GLVERTEXARRAYVERTEXOFFSETEXT)
	LOAD(glVertexArrayColorOffsetEXT, GLVERTEXARRAYCOLOROFFSETEXT)
	LOAD(glVertexArrayEdgeFlagOffsetEXT, GLVERTEXARRAYEDGEFLAGOFFSETEXT)
	LOAD(glVertexArrayIndexOffsetEXT, GLVERTEXARRAYINDEXOFFSETEXT)
	LOAD(glVertexArrayNormalOffsetEXT, GLVERTEXARRAYNORMALOFFSETEXT)
	LOAD(glVertexArrayTexCoordOffsetEXT, GLVERTEXARRAYTEXCOORDOFFSETEXT)
	LOAD(glVertexArrayMultiTexCoordOffsetEXT, GLVERTEXARRAYMULTITEXCOORDOFFSETEXT)
	LOAD(glVertexArrayFogCoordOffsetEXT, GLVERTEXARRAYFOGCOORDOFFSETEXT)
	LOAD(glVertexArraySecondaryColorOffsetEXT, GLVERTEXARRAYSECONDARYCOLOROFFSETEXT)
	LOAD(glVertexArrayVertexAttribOffsetEXT, GLVERTEXARRAYVERTEXATTRIBOFFSETEXT)
	LOAD(glVertexArrayVertexAttribIOffsetEXT, GLVERTEXARRAYVERTEXATTRIBIOFFSETEXT)
	LOAD(glEnableVertexArrayEXT, GLENABLEVERTEXARRAYEXT)
	LOAD(glDisableVertexArrayEXT, GLDISABLEVERTEXARRAYEXT)
	LOAD(glEnableVertexArrayAttribEXT, GLENABLEVERTEXARRAYATTRIBEXT)
	LOAD(glDisableVertexArrayAttribEXT, GLDISABLEVERTEXARRAYATTRIBEXT)
	LOAD(glGetVertexArrayIntegervEXT, GLGETVERTEXARRAYINTEGERVEXT)
	LOAD(glGetVertexArrayPointervEXT, GLGETVERTEXARRAYPOINTERVEXT)
	LOAD(glGetVertexArrayIntegeri_vEXT, GLGETVERTEXARRAYINTEGERI_VEXT)
	LOAD(glGetVertexArrayPointeri_vEXT, GLGETVERTEXARRAYPOINTERI_VEXT)
	LOAD(glMapNamedBufferRangeEXT, GLMAPNAMEDBUFFERRANGEEXT)
	LOAD(glFlushMappedNamedBufferRangeEXT, GLFLUSHMAPPEDNAMEDBUFFERRANGEEXT)
IF(ARB_buffer_storage)
	LOAD(glNamedBufferStorageEXT, GLNAMEDBUFFERSTORAGEEXT)
ENDIF
IF(ARB_clear_buffer_object)
	LOAD(glClearNamedBufferDataEXT, GLCLEARNAMEDBUFFERDATAEXT)
	LOAD(glClearNamedBufferSubDataEXT, GLCLEARNAMEDBUFFERSUBDATAEXT)
ENDIF
IF(ARB_framebuffer_no_attachments)
	LOAD(glNamedFramebufferParameteriEXT, GLNAMEDFRAMEBUFFERPARAMETERIEXT)
	LOAD(glGetNamedFramebufferParameterivEXT, GLGETNAMEDFRAMEBUFFERPARAMETERIVEXT)
ENDIF
IF(ARB_texture_buffer_range)
	LOAD(glTextureBufferRangeEXT, GLTEXTUREBUFFERRANGEEXT)
ENDIF
IF(ARB_texture_storage)
	LOAD(glTextureStorage1DEXT, GLTEXTURESTORAGE1DEXT)
	LOAD(glTextureStorage2DEXT, GLTEXTURESTORAGE2DEXT)
	LOAD(glTextureStorage3DEXT, GLTEXTURESTORAGE3DEXT)
ENDIF
IF(ARB_texture_storage_multisample)
	LOAD(glTextureStorage2DMultisampleEXT, GLTEXTURESTORAGE2DMULTISAMPLEEXT)
	LOAD(glTextureStorage3DMultisampleEXT, GLTEXTURESTORAGE3DMULTISAMPLEEXT)
ENDIF
IF(ARB_vertex_attrib_binding)
	LOAD(glVertexArrayBindVertexBufferEXT, GLVERTEXARRAYBINDVERTEXBUFFEREXT)
	LOAD(glVertexArrayVertexAttribFormatEXT, GLVERTEXARRAYVERTEXATTRIBFORMATEXT)
	LOAD(glVertexArrayVertexAttribIFormatEXT, GLVERTEXARRAYVERTEXATTRIBIFORMATEXT)
	LOAD(glVertexArrayVertexAttribLFormatEXT, GLVERTEXARRAYVERTEXATTRIBLFORMATEXT)
	LOAD(glVertexArrayVertexAttribBindingEXT, GLVERTEXARRAYVERTEXATTRIBBINDINGEXT)
	LOAD(glVertexArrayVertexBindingDivisorEXT, GLVERTEXARRAYVERTEXBINDINGDIVISOREXT)
ENDIF
IF(EXT_vertex_attrib_64bit)
	LOAD(glVertexArrayVertexAttribLOffsetEXT, GLVERTEXARRAYVERTEXATTRIBLOFFSETEXT)
ENDIF
IF(ARB_sparse_texture)
	LOAD(glTexturePageCommitmentEXT, GLTEXTUREPAGECOMMITMENTEXT)
ENDIF
IF(ARB_instanced_arrays)
	LOAD(glVertexArrayVertexAttribDivisorEXT, GLVERTEXARRAYVERTEXATTRIBDIVISOREXT)
ENDIF
END
*/

#if GLVERSION < 450
#ifdef GL_DSA
    REQUIRE(ARB_direct_state_access)
    /*LOAD(glCreateTransformFeedbacks, GLCREATETRANSFORMFEEDBACKS)*/
    /*LOAD(glTransformFeedbackBufferBase, GLTRANSFORMFEEDBACKBUFFERBASE)*/
    /*LOAD(glTransformFeedbackBufferRange, GLTRANSFORMFEEDBACKBUFFERRANGE)*/
    /*LOAD(glGetTransformFeedbackiv, GLGETTRANSFORMFEEDBACKIV)*/
    /*LOAD(glGetTransformFeedbacki_v, GLGETTRANSFORMFEEDBACKI_V)*/
    /*LOAD(glGetTransformFeedbacki64_v, GLGETTRANSFORMFEEDBACKI64_V)*/
    LOAD(glCreateBuffers, GLCREATEBUFFERS)
        LOAD(glNamedBufferStorage, GLNAMEDBUFFERSTORAGE)
            LOAD(glNamedBufferData, GLNAMEDBUFFERDATA)
                LOAD(glNamedBufferSubData, GLNAMEDBUFFERSUBDATA)
    /*LOAD(glCopyNamedBufferSubData, GLCOPYNAMEDBUFFERSUBDATA)*/
    /*LOAD(glClearNamedBufferData, GLCLEARNAMEDBUFFERDATA)*/
    /*LOAD(glClearNamedBufferSubData, GLCLEARNAMEDBUFFERSUBDATA)*/
    /*LOAD(glMapNamedBufferRange, GLMAPNAMEDBUFFERRANGE)*/
    /*LOAD(glUnmapNamedBuffer, GLUNMAPNAMEDBUFFER)*/
    /*LOAD(glFlushMappedNamedBufferRange, GLFLUSHMAPPEDNAMEDBUFFERRANGE)*/
    /*LOAD(glGetNamedBufferParameteriv, GLGETNAMEDBUFFERPARAMETERIV)*/
    /*LOAD(glGetNamedBufferParameteri64v, GLGETNAMEDBUFFERPARAMETERI64V)*/
    /*LOAD(glGetNamedBufferPointerv, GLGETNAMEDBUFFERPOINTERV)*/
    /*LOAD(glGetNamedBufferSubData, GLGETNAMEDBUFFERSUBDATA)*/
    LOAD(glCreateFramebuffers, GLCREATEFRAMEBUFFERS)
        LOAD(glNamedFramebufferRenderbuffer, GLNAMEDFRAMEBUFFERRENDERBUFFER)

    /*LOAD(glNamedFramebufferParameteri, GLNAMEDFRAMEBUFFERPARAMETERI)*/
    LOAD(glNamedFramebufferTexture, GLNAMEDFRAMEBUFFERTEXTURE)
    /*LOAD(glNamedFramebufferTextureLayer, GLNAMEDFRAMEBUFFERTEXTURELAYER)*/
    /*LOAD(glNamedFramebufferDrawBuffer, GLNAMEDFRAMEBUFFERDRAWBUFFER)*/
    LOAD(glNamedFramebufferDrawBuffers, GLNAMEDFRAMEBUFFERDRAWBUFFERS)
    /*LOAD(glNamedFramebufferReadBuffer, GLNAMEDFRAMEBUFFERREADBUFFER)*/
    LOAD(glInvalidateNamedFramebufferData, GLINVALIDATENAMEDFRAMEBUFFERDATA)
    /*LOAD(glInvalidateNamedFramebufferSubData, GLINVALIDATENAMEDFRAMEBUFFERSUBDATA)*/
    LOAD(glClearNamedFramebufferiv, GLCLEARNAMEDFRAMEBUFFERIV)
    /*LOAD(glClearNamedFramebufferuiv, GLCLEARNAMEDFRAMEBUFFERUIV)*/
    LOAD(glClearNamedFramebufferfv, GLCLEARNAMEDFRAMEBUFFERFV)
        LOAD(glClearNamedFramebufferfi, GLCLEARNAMEDFRAMEBUFFERFI)
            LOAD(glBlitNamedFramebuffer, GLBLITNAMEDFRAMEBUFFER)
                LOAD(glCheckNamedFramebufferStatus, GLCHECKNAMEDFRAMEBUFFERSTATUS)
    /*LOAD(glGetNamedFramebufferParameteriv, GLGETNAMEDFRAMEBUFFERPARAMETERIV)*/
    /*LOAD(glGetNamedFramebufferAttachmentParameteriv, GLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIV)*/
    LOAD(glCreateRenderbuffers, GLCREATERENDERBUFFERS)
        LOAD(glNamedRenderbufferStorage, GLNAMEDRENDERBUFFERSTORAGE)
    /*LOAD(glNamedRenderbufferStorageMultisample, GLNAMEDRENDERBUFFERSTORAGEMULTISAMPLE)*/
    /*LOAD(glGetNamedRenderbufferParameteriv, GLGETNAMEDRENDERBUFFERPARAMETERIV)*/
    LOAD(glCreateTextures, GLCREATETEXTURES)
    /*LOAD(glTextureBuffer, GLTEXTUREBUFFER)*/
    /*LOAD(glTextureBufferRange, GLTEXTUREBUFFERRANGE)*/
    /*LOAD(glTextureStorage1D, GLTEXTURESTORAGE1D)*/
    LOAD(glTextureStorage2D, GLTEXTURESTORAGE2D)
    //LOAD(glTextureStorage3D, GLTEXTURESTORAGE3D)
    /*LOAD(glTextureStorage2DMultisample, GLTEXTURESTORAGE2DMULTISAMPLE)*/
    /*LOAD(glTextureStorage3DMultisample, GLTEXTURESTORAGE3DMULTISAMPLE)*/
    /*LOAD(glTextureSubImage1D, GLTEXTURESUBIMAGE1D)*/
    LOAD(glTextureSubImage2D, GLTEXTURESUBIMAGE2D)
    //LOAD(glTextureSubImage3D, GLTEXTURESUBIMAGE3D)
    /*LOAD(glCompressedTextureSubImage1D, GLCOMPRESSEDTEXTURESUBIMAGE1D)*/
    LOAD(glCompressedTextureSubImage2D, GLCOMPRESSEDTEXTURESUBIMAGE2D)
    //LOAD(glCompressedTextureSubImage3D, GLCOMPRESSEDTEXTURESUBIMAGE3D)
    /*LOAD(glCopyTextureSubImage1D, GLCOPYTEXTURESUBIMAGE1D)*/
    /*LOAD(glCopyTextureSubImage2D, GLCOPYTEXTURESUBIMAGE2D)*/
    /*LOAD(glCopyTextureSubImage3D, GLCOPYTEXTURESUBIMAGE3D)*/
    /*LOAD(glTextureParameterf, GLTEXTUREPARAMETERF)*/
    /*LOAD(glTextureParameterfv, GLTEXTUREPARAMETERFV)*/
    LOAD(glTextureParameteri, GLTEXTUREPARAMETERI)
    /*LOAD(glTextureParameterIiv, GLTEXTUREPARAMETERIIV)*/
    /*LOAD(glTextureParameterIuiv, GLTEXTUREPARAMETERIUIV)*/
    /*LOAD(glTextureParameteriv, GLTEXTUREPARAMETERIV)*/
    LOAD(glGenerateTextureMipmap, GLGENERATETEXTUREMIPMAP)
        LOAD(glBindTextureUnit, GLBINDTEXTUREUNIT)

    /*LOAD(glGetTextureImage, GLGETTEXTUREIMAGE)*/
    /*LOAD(glGetCompressedTextureImage, GLGETCOMPRESSEDTEXTUREIMAGE)*/
    /*LOAD(glGetTextureLevelParameterfv, GLGETTEXTURELEVELPARAMETERFV)*/
    /*LOAD(glGetTextureLevelParameteriv, GLGETTEXTURELEVELPARAMETERIV)*/
    /*LOAD(glGetTextureParameterfv, GLGETTEXTUREPARAMETERFV)*/
    /*LOAD(glGetTextureParameterIiv, GLGETTEXTUREPARAMETERIIV)*/
    /*LOAD(glGetTextureParameterIuiv, GLGETTEXTUREPARAMETERIUIV)*/
    /*LOAD(glGetTextureParameteriv, GLGETTEXTUREPARAMETERIV)*/
    LOAD(glCreateVertexArrays, GLCREATEVERTEXARRAYS)
        LOAD(glDisableVertexArrayAttrib, GLDISABLEVERTEXARRAYATTRIB)
            LOAD(glEnableVertexArrayAttrib, GLENABLEVERTEXARRAYATTRIB)
                LOAD(glVertexArrayElementBuffer, GLVERTEXARRAYELEMENTBUFFER)
                    LOAD(glVertexArrayVertexBuffer, GLVERTEXARRAYVERTEXBUFFER)
    /*LOAD(glVertexArrayVertexBuffers, GLVERTEXARRAYVERTEXBUFFERS)*/

    LOAD(glVertexArrayAttribBinding, GLVERTEXARRAYATTRIBBINDING)
        LOAD(glVertexArrayAttribFormat, GLVERTEXARRAYATTRIBFORMAT)
/*LOAD(glVertexArrayAttribLFormat, GLVERTEXARRAYATTRIBLFORMAT)*/
/*LOAD(glVertexArrayBindingDivisor, GLVERTEXARRAYBINDINGDIVISOR)*/
/*LOAD(glGetVertexArrayiv, GLGETVERTEXARRAYIV)*/
/*LOAD(glGetVertexArrayIndexediv, GLGETVERTEXARRAYINDEXEDIV)*/
/*LOAD(glGetVertexArrayIndexed64iv, GLGETVERTEXARRAYINDEXED64IV)*/
/*LOAD(glCreateSamplers, GLCREATESAMPLERS)*/
/*LOAD(glCreateProgramPipelines, GLCREATEPROGRAMPIPELINES)*/
/*LOAD(glCreateQueries, GLCREATEQUERIES)*/
/*LOAD(glGetQueryBufferObjecti64v, GLGETQUERYBUFFEROBJECTI64V)*/
/*LOAD(glGetQueryBufferObjectiv, GLGETQUERYBUFFEROBJECTIV)*/
/*LOAD(glGetQueryBufferObjectui64v, GLGETQUERYBUFFEROBJECTUI64V)*/
/*LOAD(glGetQueryBufferObjectuiv, GLGETQUERYBUFFEROBJECTUIV)*/
#endif
#endif

            OPTIONAL(ARB_clip_control)
                LOAD(glClipControl, GLCLIPCONTROL)
                    END

#ifdef _WIN32
    CHECK_WGL(EXT_swap_interval)
#endif
#ifdef GL_DEBUG_CONTEXT
        REQUIRE(ARB_debug_output)
            LOAD(glDebugMessageCallbackARB, GLDEBUGMESSAGECALLBACKARB)
                LOAD(glDebugMessageInsertARB, GLDEBUGMESSAGEINSERTARB)
                    LOAD(glDebugMessageControlARB, GLDEBUGMESSAGECONTROLARB)
#endif
#endif

#ifdef __cplusplus
}
#endif
