// warning this file is generated by a tool do not modify

/* ===========================================================================
 *
 * Copyright (c) 2020-2021 Disney Streaming Technology LLC.All rights reserved.
 *
 * ==========================================================================*/

#if defined(_VADER)
#include "source/shaders/compiled/vader/canvas_video.frag.gen.h"
#elif defined(_LEIA)
#include "source/shaders/compiled/leia/canvas_video.frag.gen.h"
#else
#include "source/shaders/compiled/glsl/canvas_video.frag.gen.h"
#endif