// warning this file is generated by a tool do not modify

/* ===========================================================================
 *
 * Copyright (c) 2020-2021 Disney Streaming Technology LLC. All rights reserved.
 *
 * ==========================================================================*/

#if defined(_VADER)
#include "source/shaders/compiled/vader/canvas.vert.gen.h"
#elif defined(_LEIA)
#include "source/shaders/compiled/leia/canvas.vert.gen.h"
#else
#include "source/shaders/compiled/glsl/canvas.vert.gen.h"
#endif